# Generated by Django 2.1.3 on 2018-11-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perriblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
